"""Archive & version management for all generated content."""

import sys
import shutil
from datetime import datetime
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from core.db import FactoryDB


class Archive:
    """Archive all generated content for search & retrieval."""

    def __init__(self, db=None, output_dir="output"):
        self.db = db or FactoryDB()
        self.output_dir = Path(output_dir)

    def get_all(self, limit=50):
        """Get all archived content."""
        return self.db.query(
            "SELECT content_id, type, topic, tone, status, created_at, updated_at, tags "
            "FROM content ORDER BY created_at DESC LIMIT ?",
            [limit]
        )

    def search(self, keyword):
        """Search archived content by keyword."""
        like = f"%{keyword}%"
        return self.db.query(
            "SELECT content_id, type, topic, status, created_at FROM content "
            "WHERE topic LIKE ? OR caption LIKE ? OR tags LIKE ? "
            "ORDER BY created_at DESC LIMIT 20",
            [like, like, like]
        )

    def by_tag(self, tag):
        """Find content by tag."""
        return self.db.query(
            "SELECT content_id, type, topic, status, created_at FROM content "
            "WHERE tags LIKE ? ORDER BY created_at DESC LIMIT 20",
            [f"%{tag}%"]
        )

    def by_type(self, content_type):
        """Find content by type."""
        return self.db.query(
            "SELECT content_id, topic, status, created_at FROM content "
            "WHERE type = ? ORDER BY created_at DESC LIMIT 20",
            [content_type]
        )

    def export_content(self, content_id, export_dir=None):
        """Export content to a shareable file."""
        row = self.db.query("SELECT * FROM content WHERE content_id = ?", [content_id])
        if not row:
            return None

        row = row[0]
        if export_dir is None:
            export_dir = self.output_dir / "exports"
        export_dir = Path(export_dir)
        export_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{content_id}_{row['topic'].replace(' ', '_')[:30]}.txt"
        filepath = export_dir / filename

        content = f"""# {row['topic']}
Type: {row['type']}
Tone: {row['tone']}
Status: {row['status']}
Created: {row['created_at']}
Tags: {row['tags']}

---

{row['caption']}

---
Generated by Neville Goddard Content Factory v1.0
@nevgoinstitute
"""

        filepath.write_text(content, encoding="utf-8")
        return str(filepath)
